# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: mysql:8.0.28
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: fastapi
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
