CREATE DATABASE fastapi CHARACTER SET 'utf8mb4';
CREATE DATABASE fastapi_test CHARACTER SET 'utf8mb4';

GRANT ALL PRIVILEGES ON fastapi.* TO fastapi@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON fastapi_test.* TO fastapi@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

USE fastapi;